version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: jobcatcher_postgres
    restart: always
    environment:
      POSTGRES_USER: jobcatcher
      POSTGRES_PASSWORD: jobcatcherpass
      POSTGRES_DB: jobcatcher
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    build: .
    container_name: jobcatcher_bot
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: jobcatcher
      DB_USER: jobcatcher
      DB_PASSWORD: jobcatcherpass

volumes:
  postgres_data: